### PR TITLE
fix: removed unused effect

### LINKED ISSUE #1350: chore(feed): Remove this useless useEffect used for Video render
It's here: https://github.com/TERITORI/teritori-dapp/blob/main/packages/screens/FeedPostView/components/FeedPostDefaultView.tsx#L57-L62

Why removing that ?

`FeedPostDefaultView` is only called in `FeedPostView`, but this `useEffect` redirects to `FeedPostView`.
Also, the `PostCategory.Video` case is already handled in `FeedPostView`: https://github.com/TERITORI/teritori-dapp/blob/main/packages/screens/FeedPostView/FeedPostView.tsx#L81-L82.
So, there is no reason to redirect to `FeedPostView` for the `PostCategory.Video` case

### PR DESCRIPTION
**Pull request by addegbenga**
Remove unused useEffect from FeedPostDefaultView screen
Fixes #1350

I just opened a new PR with the exact same changes to get CI Right.
[PR](https://github.com/TERITORI/teritori-dapp/pull/1427)

### CODE REVIEW

**Review by WaDadidou — APPROVED** [review]
LGTM, thank you

**Comment by clegirar** [comment]
@addegbenga Thanks for your contribution 👍 
Normally you have received an invitation to have rights in the repo (some CI jobs needs some secrets that are fetchable only from people that have some minimum rights in the repo), so can you just accept it and tell us when it's done ?

**Comment by addegbenga** [comment]
> @addegbenga Thanks for your contribution 👍 Normally you have received an invitation to have rights in the repo (some CI jobs needs some secrets that are fetchable only from people that have some minimum rights in the repo), so can you just accept it and tell us when it's done ?

Appreciate, and yeah I just accepted the invite.

**Comment by clegirar** [comment]
Can you open a new branch in the Teritori repository ? And not in your fork, with the same changes ?

**Comment by addegbenga** [comment]
> @addegbenga Can you open a new branch in the Teritori repository ? And not in your fork, with the same changes ? (I think CI jobs from fork branches are not allowed to fetch secrets)

Okay , I just did that now kindly check.


> @addegbenga Can you open a new branch in the Teritori repository ? And not in your fork, with the same changes ? (I think CI jobs from fork branches are not allowed to fetch secrets)

Alright , I just did now [c](https://github.com/TERITORI/teritori-dapp/tree/remove_effect)

**Comment by clegirar** [comment]
Okay can you open a PR of this branch, and notify in this PR that you opened a new PR with exact changes to have CI jobs rights ?

**Pull request closed without merging**
