### PR TITLE
feat: mobile RIOT p2e

### PR DESCRIPTION
**Pull request by omniwired**

### CODE REVIEW

**Comment by WaDadidou** [comment]
What would be the minimum screen size for this feature on mobile ?
The deisgn is broken on 360px 
image

The `Video` on `/riot-game/enroll` starts to be croped under 486px and the rest the this page design starts to be croped under 380px

**Comment by WaDadidou** [comment]
Could you replace this `paddingLeft` by `paddingHorizontal` to make a right space between `TopLogo` and the horizontal menu (`ScrollView`) ? 
Here: https://github.com/TERITORI/teritori-dapp/blob/205033ec29f6ec3bb5e2ce179c1e7f71cefbc22c/packages/components/navigation/components/TopLogo.tsx#L32
image

**Comment by WaDadidou** [comment]
Maybe it's out of socpe, but when no wallet is connected, the Price currency is broken on `/riot-game/breeding`
image

**Comment by WaDadidou** [comment]
Could you replace this `marginRight` by `marginHorizontal` to make a left space between the "Squad 1-2" button and the title (`BrandText`) ? 
Issue on `/riot-game/enroll`, from 418px to 440px width
Here: https://github.com/TERITORI/teritori-dapp/blob/9bc94596dbafaf5579e9debb88eae44a0c3346f0/packages/screens/RiotGame/RiotGameEnrollScreen.tsx#L309

image

**Review by WaDadidou — CHANGES_REQUESTED** [review]

**Comment by WaDadidou** [comment]
Could you make this, (or maybe it's out of scope): On the header, when press an item, scroll horizontaly to this item. 
I made a PR https://github.com/TERITORI/teritori-dapp/pull/707 about this (that concerns `Tabs`), maybe we can something like in `RiotGameHeader` ?

image

**Comment by omniwired** [comment]
> What would be the minimum screen size for this feature on mobile ? The deisgn is broken on 360px image
> 
> The `Video` on `/riot-game/enroll` starts to be croped under 486px and the rest the this page design starts to be croped under 380px

I target 390 x 844

https://yesviz.com/iphones.php

**Review by hthieu1110 — APPROVED** [review]
LGTM

**Pull request merged**
