### PR TITLE
feat: improve app switch logic and add logo customization

### PR DESCRIPTION
**Pull request by n0izn0iz**
- Improved the app switch to not edit `package.json`
- Added a way to customize the top logo and added gnotribe tmp top logo
- Added gnotribe icon

### CODE REVIEW

**Comment by hthieu1110** [comment]
Should we add app-switch.config.example to the repo ? if not then someone later has to ask how it looks like the content of app-switch :-s

**Comment by n0izn0iz** [comment]
why? it's committed as you can see in the diff

**Comment by n0izn0iz** [comment]
actually this creates a diff unless you run specific update-index commands locally :/
also the android build seem to do funny business with the app config so the switch doesn't work

**Review by MikaelVallenet — APPROVED** [review]
I approve because the working flow looks good to me,
Some idea, what about renaming ``gno-dapp`` -> ``gnotribe-dapp``, it's more explicit since the product is name gnotribe

could also be nice in a script when an app is not found to list the existing app (just list name of folders in ``apps`` to get this informations

**Review by clegirar — APPROVED** [review]
Tested it and it works well 👍 
Cool to have an alternative without change `package.json`

And the error message with available apps is good

**Review by MikaelVallenet — APPROVED** [review]

**Pull request merged**
