### PR TITLE
fix(social feed): scrollbar on emoji list

### LINKED ISSUE #542: Social feed: fix the scrollbar on emoji list
Upon clicking on the emoji icon to pop-up the emoji modal, the scroolbar overflows on the emojis list. Maybe adding a little bit of padding/margin would do the trick (as seen on Twitter for instance).
image

### PR DESCRIPTION
**Pull request by omniwired**
Fixes #542 

Fixed:

Looks like this

Kapture 2023-04-13 at 11 30 07

### CODE REVIEW

**Comment by n0izn0iz** [comment]
I have the same behavior on main and this branch

**Comment by omniwired** [comment]
Which browser?

**Comment by n0izn0iz** [comment]
ff and chrome

**Comment by omniwired** [comment]
I also see it fixed on prod!
seems it got fixed by another PR.
Closing it then.

**Pull request closed without merging**
