### PR TITLE
feat: add scripts to build cosmwasm contract with optimizer

### PR DESCRIPTION
**Pull request by hthieu1110**

### CODE REVIEW

**Comment by n0izn0iz** [comment]
I have `Usage: /usr/local/bin/optimize.sh DIRECTORY` error

**Comment by n0izn0iz** [comment]
also the platform should be forced to linux/amd64

**Comment by n0izn0iz** [comment]
I made the changes

**Review by WaDadidou — APPROVED** [review]
Works well :)

**Review by n0izn0iz — APPROVED** [review]
LGTM

**Pull request merged**
