### PR TITLE
dosc: readme

### PR DESCRIPTION
**Pull request by Olexandr88**
Added name and twitter link

### CODE REVIEW

**Comment by n0izn0iz** [comment]
please make meaningful contribution and stop spam readme changes in all crypto github

**Comment by Olexandr88** [comment]
So I agree with you that it looks like spam on your background. But I'm still learning, and even those skills are an accomplishment for me today. I am currently active on OnlyDust and have earned my first $24, which is not bad for me as a citizen of a country that has been at war for almost three years. You better tell me what I need to learn, some material for development, to develop further. Thank you

**Comment by Olexandr88** [comment]
Знімок екрана 2024-11-21 о 22 00 22

**Comment by n0izn0iz** [comment]
okay, do this task then: https://github.com/TERITORI/teritori-dapp/issues/1395
I pay you 5$ in tori if you do it

**Pull request closed without merging**
